"""
Analyzer Package Facade
=======================
Reader Applicative 抽象化を用いた特徴量抽出器およびデータ構造を再エクスポートしますの。
後方互換性を 100% 保証するための統合エントリーポイントですわ！
"""

from .core import (
    FIXED_SEQ_FRAMES,
    LIBROSA_LOCK,
    TONNETZ_N_FRAMES,
    AudioContext,
    FeatureExtractor,
    StemContext,
    _resample_to_fixed_frames,
    product_all,
)
from .essentia_dsp import (
    _calc_chord_sequence,
    _calc_vocal_f0_seq,
    extract_mel_patches,
    run_essentia_serialized,
)
from .librosa_dsp import (
    STEM_CONFIGS,
    LibrosaFeatures,
    _calc_hnr_db,
    _calc_nap_from_hnr_db,
    extract_beat_regularity,
    extract_beat_stability,
    extract_bpm,
    extract_centroid_obj,
    extract_chroma_obj,
    extract_contrast,
    extract_crest_factor,
    extract_dominant_pitch,
    extract_energy,
    extract_flatness,
    extract_groove,
    extract_hilbert,
    extract_hnr,
    extract_hnr_db,
    extract_key,
    extract_mfcc_obj,
    extract_mfccs,
    extract_nap,
    extract_onset,
    extract_peak,
    extract_rms_mean,
    extract_rms_obj,
    extract_rms_peak,
    extract_rolloff,
    extract_scipy_stats,
    extract_section,
    extract_snr,
    extract_spectral_bandwidth,
    extract_spectral_centroid_mean,
    extract_spectral_centroid_sd,
    extract_tempogram,
    extract_temporal_seq,
    extract_tonnetz,
    extract_vocal_f0,
    extract_zcr,
    librosa_extractor,
    librosa_extractor_v4,
    stem_extractor,
)
from .registry_plugins import (
    BasePlugin,
    PluginMetadata,
    PluginRegistry,
    register_plugin,
)
from .stats import (
    _calc_hilbert_features,
    _calc_peak_features,
    _calc_scipy_stats_features,
    _calc_time_entropy,
)
# 遅延インポート用定義 (PyTorch / CUDA DLL の早期衝突防止)
_LAZY_TENSOR_EXPORTS = {
    "extract_tensor_features",
    "extract_tensor_obj",
    "fft_bandpass_envelope",
    "hilbert_envelope_phase",
    "tensor_extractor",
    "welch_psd",
}
from .types_features import (
    AudioCutoffLufsFeatures,
    ChromaFeatures,
    DemucsFeatures,
    EssentiaFeatures,
    GrooveFeatures,
    HilbertFeatures,
    KeyFeatures,
    MfccFeatures,
    OnsetFeatures,
    PeakFeatures,
    PsychoacousticsFeatures,
    RawFeatures,
    RmsFeatures,
    ScipyStatsFeatures,
    SectionFeatures,
    SpectralCentroidFeatures,
    SpectralRolloffFeatures,
    StemFeatures,
    StructureSsmFeatures,
    TempogramFeatures,
    TemporalSeqFeatures,
    TensorFeatures,
    TonnetzFeatures,
    VoiceCppFeatures,
    ZcrFeatures,
    _safe_float_str,
    _safe_int,
    _stem_filter_scalars,
    _stem_filter_sequences,
)

__all__ = [
    "AudioContext",
    "StemContext",
    "FeatureExtractor",
    "product_all",
    "LIBROSA_LOCK",
    "FIXED_SEQ_FRAMES",
    "TONNETZ_N_FRAMES",
    "_resample_to_fixed_frames",
    "RawFeatures",
    "StemFeatures",
    "TensorFeatures",
    "TonnetzFeatures",
    "SectionFeatures",
    "GrooveFeatures",
    "TemporalSeqFeatures",
    "MfccFeatures",
    "SpectralCentroidFeatures",
    "RmsFeatures",
    "SpectralRolloffFeatures",
    "ZcrFeatures",
    "ChromaFeatures",
    "DemucsFeatures",
    "KeyFeatures",
    "TempogramFeatures",
    "OnsetFeatures",
    "ScipyStatsFeatures",
    "HilbertFeatures",
    "PeakFeatures",
    "EssentiaFeatures",
    "PsychoacousticsFeatures",
    "StructureSsmFeatures",
    "VoiceCppFeatures",
    "AudioCutoffLufsFeatures",
    "PluginRegistry",
    "BasePlugin",
    "PluginMetadata",
    "register_plugin",
    "extract_hnr",
    "extract_hnr_db",
    "extract_nap",
    "extract_key",
    "extract_mfcc_obj",
    "extract_mfccs",
    "extract_onset",
    "extract_peak",
    "extract_rms_mean",
    "extract_rms_obj",
    "extract_rms_peak",
    "extract_rolloff",
    "extract_scipy_stats",
    "extract_section",
    "extract_snr",
    "extract_spectral_bandwidth",
    "extract_spectral_centroid_mean",
    "extract_spectral_centroid_sd",
    "extract_tempogram",
    "extract_temporal_seq",
    "extract_tonnetz",
    "extract_vocal_f0",
    "extract_zcr",
    "extract_tensor_features",
    "extract_tensor_obj",
    "tensor_extractor",
    "hilbert_envelope_phase",
    "welch_psd",
    "fft_bandpass_envelope",
    "extract_mel_patches",
    "run_essentia_serialized",
    "librosa_extractor",
    "librosa_extractor_v4",
    "stem_extractor",
    "STEM_CONFIGS",
    "_safe_int",
    "_safe_float_str",
    "_stem_filter_scalars",
    "_stem_filter_sequences",
    "_calc_hnr_db",
    "_calc_nap_from_hnr_db",
    "_calc_time_entropy",
    "_calc_scipy_stats_features",
    "_calc_hilbert_features",
    "_calc_chord_sequence",
    "_calc_vocal_f0_seq",
]


def __getattr__(name: str):
    """PyTorch / Tensor DSP 関数のオンデマンド遅延インポートですわ！"""
    if name in _LAZY_TENSOR_EXPORTS:
        from . import tensor_dsp

        val = getattr(tensor_dsp, name)
        globals()[name] = val
        return val
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")


def __dir__():
    return sorted(list(globals().keys()) + list(_LAZY_TENSOR_EXPORTS))
